[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[context.deploy-preview.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[context.branch-deploy.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"


