[build]
  command = "npm run build"
  publish = "Frontend/build"

[[plugins]]
  package = "netlify-plugin-a11y"
  [plugins.inputs]
    checkPaths = ["/"]

[[plugins]]
  package = "netlify-plugin-fetch-feeds"
  [plugins.inputs]
    dataDir = "Frontend/build/feeds"

    [[plugins.inputs.feeds]]
      name = "hawksworx"
      url = "https://hawksworx.com/feed.json"
      ttl = 86400

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
